name: flutter_application_3
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: 6.1.0
  isar: 3.1.0+1
  isar_flutter_libs: 3.1.0+1
  path_provider: 2.1.2
  popover: ^0.3.0
  provider: 6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.2
  isar_generator: 3.1.0+1
  build_runner: 2.4.9

flutter:
  uses-material-design: true
